// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVkRsAA2RCTZvpAHnz8cdgfgKK1NhsqPU',
    appId: '1:1062038376839:web:5e31b190604aa4c86ec322',
    messagingSenderId: '1062038376839',
    projectId: 'tvoberwil-b9e3b',
    authDomain: 'tvoberwil-b9e3b.firebaseapp.com',
    storageBucket: 'tvoberwil-b9e3b.firebasestorage.app',
    measurementId: 'G-S550CEGRWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lq6-RxQ3bIzQVFS1OUpd6Ac1qQKi-ME',
    appId: '1:1062038376839:android:731053965f42b2bc6ec322',
    messagingSenderId: '1062038376839',
    projectId: 'tvoberwil-b9e3b',
    storageBucket: 'tvoberwil-b9e3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qMLXSTvq2Tl978ZQmj_pWoZR9OnsiMw',
    appId: '1:1062038376839:ios:6f5e55d282d8fa8f6ec322',
    messagingSenderId: '1062038376839',
    projectId: 'tvoberwil-b9e3b',
    storageBucket: 'tvoberwil-b9e3b.firebasestorage.app',
    iosBundleId: 'ch.flavianz.tvOberwil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qMLXSTvq2Tl978ZQmj_pWoZR9OnsiMw',
    appId: '1:1062038376839:ios:6f5e55d282d8fa8f6ec322',
    messagingSenderId: '1062038376839',
    projectId: 'tvoberwil-b9e3b',
    storageBucket: 'tvoberwil-b9e3b.firebasestorage.app',
    iosBundleId: 'ch.flavianz.tvOberwil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVkRsAA2RCTZvpAHnz8cdgfgKK1NhsqPU',
    appId: '1:1062038376839:web:eccb7228c5abbb4b6ec322',
    messagingSenderId: '1062038376839',
    projectId: 'tvoberwil-b9e3b',
    authDomain: 'tvoberwil-b9e3b.firebaseapp.com',
    storageBucket: 'tvoberwil-b9e3b.firebasestorage.app',
    measurementId: 'G-YBXM31Z0F1',
  );
}
